name: countdown_progress_indicator
description: Customizable countdown timer for Flutter.
version: 0.0.1
author: Andres Felipe Rojas
homepage: https://github.com/AndresR173/countdown_progress_indicator

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.0.0

# The following section is specific to Flutter.
flutter:
