name: countdown_progress_indicator
description: Customizable countdown timer for Flutter with pause/resume controls.
version: 0.1.0
homepage: https://github.com/AndresR173/countdown_progress_indicator

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.0.0

# The following section is specific to Flutter.
flutter:
